# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/sage/Apps/GameMaking/Linux_Unreal_Engine_5.6.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	FP_Cpp-Android-DebugGame  \
	FP_Cpp-Android-Development  \
	FP_Cpp-Android-Shipping  \
	FP_Cpp-Linux-DebugGame  \
	FP_Cpp-Linux-Development  \
	FP_Cpp-Linux-Shipping  \
	FP_Cpp-LinuxArm64-DebugGame  \
	FP_Cpp-LinuxArm64-Development  \
	FP_Cpp-LinuxArm64-Shipping  \
	FP_Cpp \
	FP_CppEditor-Linux-DebugGame  \
	FP_CppEditor-Linux-Development  \
	FP_CppEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend FP_CppEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug FP_CppEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

FP_Cpp-Android-DebugGame:
	 $(BUILD) FP_Cpp Android DebugGame  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-Android-Development:
	 $(BUILD) FP_Cpp Android Development  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-Android-Shipping:
	 $(BUILD) FP_Cpp Android Shipping  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-Linux-DebugGame:
	 $(BUILD) FP_Cpp Linux DebugGame  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-Linux-Development:
	 $(BUILD) FP_Cpp Linux Development  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-Linux-Shipping:
	 $(BUILD) FP_Cpp Linux Shipping  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-LinuxArm64-DebugGame:
	 $(BUILD) FP_Cpp LinuxArm64 DebugGame  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-LinuxArm64-Development:
	 $(BUILD) FP_Cpp LinuxArm64 Development  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp-LinuxArm64-Shipping:
	 $(BUILD) FP_Cpp LinuxArm64 Shipping  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_Cpp: FP_Cpp-Linux-Development

FP_CppEditor-Linux-DebugGame:
	 $(BUILD) FP_CppEditor Linux DebugGame  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_CppEditor-Linux-Development:
	 $(BUILD) FP_CppEditor Linux Development  -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" $(ARGS)

FP_CppEditor: FP_CppEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/sage/Documents/Unreal Projects/FP_Cpp/FP_Cpp.uproject" -Game 

.PHONY: $(TARGETS)
